### ISSUE TITLE
Правки

### ISSUE THREAD

**Issue by sergoio0704** [DarkMoonLi/Recipes#4]
1) В методе `AddRecipe` поменять роут на `[Route("")]`
2) В методе `AddRecipe` поменять название `ExampleDto` на `RecipeContainerDto`
3) В моделях `Recipe`, `Step` и т.д., сделать инициализацию в конструкторе, т.е. сеттеры нужно сделать приватными и устанавливать значения при создании экземпляра в конструкторе.
4) В `RecipeContainerDto ` для свойства `recipe` сделать `RecipeDto` пока что с такими же свойствами как и в `Recipe`. но `get` и `set`-ры должны быть уже с доступностью `public`
5) В `RecipeEntityConfiguration` удалить  18-19 строки
6) В методе `GetRecipeById` добавить проверку на `null`. чтобы избежать ситуации, когда в базе мы не нашли рецепт по определенному `Id`

**Comment by loise322** [comment]
1. (К пункту 6 у Сергея) Вместо проверки на null, можно сделать FirstOrDefault( x => x.Id == id ), т.е. у нас либо найдет рецепт по айди либо вернёт null и не будет никаких NullReferenceException. Советую побольше почитать про LINQ и лямбда-выражения, там много интересного.
2. Вынести RecipeRepository.cs и IRecipeRepository.cs в Infrastucture, можно создать внутри папку Repositories.
